### отправка смс
POST http://localhost:8084/api/v1/sms?clientId=1&limit=10
Content-Type: application/json

{
  "clientId": 1,
  "smsText": "Привет! это тестовая SMS",
  "receiverPhoneNumber": "+7-999-999-00-00"
}


### получение списка sms по клиенту
GET http://localhost:8084/api/v1/sms?clientId=133&limit=10
Accept: application/json


### получение списка sms по клиенту, которого нет -> ошибка
GET http://localhost:8084/api/v1/sms?clientId=133&limit=10
Accept: application/json

